kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

nodes:
- role: control-plane
- role: worker
  extraMounts:
  - hostPath: /tmp/bpf-map/
    containerPath: /tmp/bpf-map/
    propagation: Bidirectional
    selinuxRelabel: false
- role: worker
  extraMounts:
  - hostPath: /tmp/bpf-map2/
    containerPath: /tmp/bpf-map/
    propagation: Bidirectional
    selinuxRelabel: false
